import fs from 'node:fs';
import assert from 'node:assert/strict';
const audio=fs.readFileSync(new URL('../src/audio/AudioEngine.js',import.meta.url),'utf8');
const main=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../web/index.html',import.meta.url),'utf8');
for(const token of ['createDynamicsCompressor','cueStrike(power=.5)','ballCollision(impulse=.1)','cushion(impulse=.1)','pocket(ball)','offTable()','foul()','score(value=1)','turn()','frameWin()','updateRolling(world)'])assert.ok(audio.includes(token),`missing premium audio foundation contract: ${token}`);
const vol=html.match(/id="soundVolume"[^>]*max="(\d+)"[^>]*value="(\d+)"/);assert.ok(vol&&+vol[1]>=300&&+vol[2]>=300,'volume control must preserve at least the v5.6 300% loudness capability');
assert.match(main,/audio\.turn\(\)/,'turn transition must have audio feedback');
assert.match(main,/world\.onOffTable=b=>\{audio\.offTable\(\)/,'off-table event must have premium impact feedback');
console.log('PASS v5.6 premium audio foundation remains present');
